# Generated by Django 6.0.4 on 2026-04-26 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScraperJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("searching", "Searching Google Maps"),
                            ("fetching", "Fetching Details"),
                            ("cleaning", "Cleaning Data"),
                            ("reading_cv", "Reading CV"),
                            ("analyzing", "AI Analysis"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("search_term", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                ("max_results", models.IntegerField(default=60)),
                ("cv_path", models.CharField(blank=True, max_length=500)),
                ("progress", models.IntegerField(default=0)),
                ("progress_message", models.CharField(blank=True, max_length=500)),
                ("log_messages", models.JSONField(default=list)),
                ("total_found", models.IntegerField(default=0)),
                ("total_leads", models.IntegerField(default=0)),
                ("leads_json", models.JSONField(blank=True, null=True)),
                ("ai_analysis", models.TextField(blank=True)),
                ("csv_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
